import type {NextPage} from 'next'
import type {AppProps} from 'next/app'
import Head from 'next/head'
import {AppWrapper} from './AppWrapper'
import styles from './app.module.scss'
import {Footer} from '@components/Footer'
import {Header} from '@components/Header'

const App: NextPage<AppProps> = ({Component, pageProps}) => (
	<AppWrapper>
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link
					rel='icon'
					href='/vercel.ico'
				/>
			</Head>

			<Header />

			<div className={styles.content}>
				{/* Component injection point is here! */}
				<Component {...pageProps} />
			</div>

			<Footer />
		</div>
	</AppWrapper>
)

export {App}
