import '@styles/globals.scss'
import type {FC} from 'react'

const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}


interface Props {
	children: React.ReactNode,
}

const RootLayout: FC<Props> = ({children}) => (
	<html lang='en'>
		<body>
			{children}
		</body>
	</html>
)

export {metadata}
export default RootLayout
