import '@styles/globals.scss'
import {AppWrapper} from '@templates/AppWrapper/AppWrapper'
import type {FC, ReactNode} from 'react'

const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

interface Props {
	children: ReactNode,
}

const RootLayout: FC<Props> = ({children}) => (
	<html lang = 'en'>
		<body>
			<AppWrapper>
				{children}
			</AppWrapper>
		</body>
	</html>
)

export {metadata}
export default RootLayout
